#!/bin/bash

flag=1
for (( i=1; i<=4 ; i++));
do
	for (( j=1; j<=i; j++));
	do
		echo -n $flag
		((flag=flag+1))
	done
	echo ""
done
#!/bin/bash

flag=10
for(( i=3; flag>0; i-- ));
do
	((temp=flag-i))
	for(( j=0; j<=i; j++ ));
	do
		echo -n $temp
		((temp=temp+1))
		((flag=flag-1))
	done
	echo ""
done
#!/bin/bash

flag=1
for(( i=0; i<3; i++ ));
do
	for(( j=2-i; j>0; j-- ));
	do
		echo -n " "
	done
	for(( k=0; k<=i; k++));
	do
		echo -n $flag" "
		((flag=flag+1))
	done
	echo ""
done

for(( i=0; i<2; i++));
do
	for(( j=0; j<=i; j++ ));
	do
		echo -n " "
	done
	for(( k=0; k<2-i; k++));
	do
		echo -n $flag" "
		((flag=flag+1))
	done
	echo ""
done
#!/bin/bash

a=0
b=1
c=0
echo -n $b
for(( i=0; i<8; i++));
do
	((c=a+b))
	echo -n ,$c
	((a=b))
	((b=c))
done
echo ""
